### ISSUE TITLE
UI for displaying the Community Covenant and signing it too.

### ISSUE THREAD

**Issue by willjgriff** [1Hive/celeste-swarm#7]
The community covenant is the text description that is associated with our 1Hive DAO. Somewhere in the honey pot UI we will need to show  the community covenant as it will be used by Celeste keepers to resolve disputes regarding 1Hive votes/proposals.

We should also add to the profile screen an indication of whether or not a user has "signed" the community covenant, implying that they have read it. There is a chance the covenant will be updated in the future, at which point all users that wish to submit votes/proposals will have to sign the covenant again.

I envision a field in the profile screen that indicates whether the current address/user has signed the current covenant. If not, they can click it and it might pop-up a modal that includes the whole covenant with a button at the bottom that submits the signature, implying they have read it. Up to you of course though whatever you think would be best.

We also need to link to this when users have not yet signed the covenant and they attempt to create a vote or a proposal.

**Comment by fioreb** [comment]
Figma link:

https://www.figma.com/file/P06HTzSyb9hExJVpwaUPmA/Honey-Pot-2.0?node-id=1705%3A0

There is the flow for a Proposal, but it will be the same for Suggestions and Decisions.
I changed the wording for the Creation modal since we don't have "Funding proposal" anymore, what do you think about that?
